{{- range .Values.projects }}
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  sourceRepos:
  -  '*'
  destinations:
  - namespace: {{ .namespace }}
    name: '*'
    server: in-cluster
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
{{- end }}