kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: gateway
  namespace: gateway
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8000
    name: http-listener
    allowedRoutes:
      namespaces:
        from: All
  - protocol: HTTPS
    port: 8443
    tls:
      mode: Terminate
      certificateRefs:
        - name: argocd-tls-secret*
          kind: Secret
    name: https-listener
    allowedRoutes:
      namespaces:
        from: All